### ISSUE TITLE
Add support for Pushover

### ISSUE THREAD

**Issue by ScumbagSteve** [foxriver76/ioBroker.notification-manager#14]
Support for Pushover notifications would be great 👍

**Comment by foxriver76** [comment]
Please open the issue at the pushover adapter with following info https://github.com/foxriver76/ioBroker.notification-manager?tab=readme-ov-file#requirements-for-messaging-adapters

**Comment by foxriver76** [comment]
Tracking at: https://github.com/ioBroker/ioBroker.pushover/issues/277
