### ISSUE TITLE
Meldungen werden nur über einen Kanal gesendet obwohl email & telegram ausgewählt sind

### ISSUE THREAD

**Issue by Diginix** [foxriver76/ioBroker.notification-manager#20]
Ich habe für alle Kategorien email und telegram ausgewählt. Erhalte aber nur über email die Meldungen.

![image](https://github.com/foxriver76/ioBroker.notification-manager/assets/39678667/4c5d38ed-4149-43a2-a836-76a4ff2b99d9)

![image](https://github.com/foxriver76/ioBroker.notification-manager/assets/39678667/6a56aaa1-b328-43f2-9e92-8adbcb5b3a13)

notification-manager: 1.1.2
js-controller: 6.0.5
nodejs: 20.15.0

**Comment by foxriver76** [comment]
Der zweite Messenger wird nur genutzt wenn der erste Probleme hat die Nachrichten zu senden.

**Comment by Diginix** [comment]
Ah, das ist ein guter Hinweis. Danke.

**Comment by foxriver76** [comment]
Falls nötig aber gerne auch als featurewunsch dass man einstellen kann, dass immer beide Kanäle genutzt werden.

**Comment by Diginix** [comment]
Mir reicht prinzipiell ein Kanal. Wusste bisher nicht, dass der zweite nur als Fallback gilt. Reicht mir so.

**Comment by Negalein** [comment]
Könntest du es machen, dass an beide Adapter gesendet wird?

Grund ist, Zuhause schau ich 99% Email. Aber unterwegs zu 99% Telegram.

**Comment by Diginix** [comment]
> Falls nötig aber gerne auch als featurewunsch dass man einstellen kann, dass immer beide Kanäle genutzt werden.

@Negalein Dann mach doch bitte ein Featurerequest auf:

**Comment by Negalein** [comment]
> @Negalein Dann mach doch bitte ein Featurerequest auf:

gerne, aber @Foxriver weiß eh Bescheid, inkl. Verlinkung hierher.
