### ISSUE TITLE
Fehlerhafte Übersetzung vom Adaptername

### ISSUE THREAD

**Issue by Lucky-ESA** [foxriver76/ioBroker.notification-manager#32]
Es werden die Adapternamen übersetzt. Sollte eventuell deaktiviert werden.
`
{
  "en": "Worx",
  "de": "Worwegen",
  "ru": "Worx",
  "pt": "Worx",
  "nl": "Worx",
  "fr": "Pire",
  "it": "Worx",
  "es": "Worx",
  "pl": "Worx",
  "uk": "Помилки",
  "zh-cn": "蠕虫"
}
`
![Screenshot 2024-09-16 204626](https://github.com/user-attachments/assets/b38a7a17-d0bd-4ad8-be5b-8b17799bd819)

**Comment by foxriver76** [comment]
Adapternamen werden nicht angezogen sondern der name des Scopes in der jeweiligen Sprache, was in deinem Fall korrekt der Adaptername ist, aber hier falsch übersetzt ist: https://github.com/iobroker-community-adapters/ioBroker.worx/blob/06592bc7e70d5e9de1a8cca488f875e987e3f1e9/io-package.json#L285

**Comment by Lucky-ESA** [comment]
Danke für die Info.
