### ISSUE TITLE
Fallback settings don't seem to be working (or needs more explanation, or maybe Telegram integration is broken)

### ISSUE THREAD

**Issue by raintonr** [foxriver76/ioBroker.notification-manager#5]
I would assume (because not mentioned on the settings page - please add a simple one line explanation) that where an adapter is not chosen on the 'Main Settings' tab, send should occur based on the fallback for that severity level.

This does not seem to happen though.

Eg. say one has this:

![image](https://github.com/foxriver76/ioBroker.notification-manager/assets/3794098/4de0b7c2-58d0-4ea3-a21b-10873377dcc8)

No adapter chosen. As fallback for severity 'alert' is configured here...

![image](https://github.com/foxriver76/ioBroker.notification-manager/assets/3794098/01b8e75f-3ba3-45f1-b657-382b99a091e7)

... I would assume all 'alert' severity should be sent to Telegram. But this doesn't happen. At least hitting the 'Send test message' button doesn't end up with a message going to Telegram even though this comes out in the log:

```
2023-07-19 08:48:41.388  - info: notification-manager.0 (31993) Send test message for scope "system" and category "memIssues"
```

TBH, this might be a deeper issue because although I have Telegram v1.16.0 installed even when selecting that adapter specifically in the main page and trying a test that doesn't work either.

Telegram certainly works in my installation as get messages from it all the time.

**Comment by foxriver76** [comment]
Js-Controller version?

**Comment by raintonr** [comment]
notification-manager.0 (2068) starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.notification-manager, node: v16.19.1, js-controller: 5.0.1-alpha.0-20230418-efa3e809

**Comment by foxriver76** [comment]
Ok you need at least 5.0.7 for the test message functionality as there has been a controller bug previously https://github.com/ioBroker/ioBroker.js-controller/commit/7c5470f2abcc79b0435c1db1449e97a69d5c0348

**Comment by raintonr** [comment]
Ah yes, that's better with 5.0.8. Maybe you could update the dependencies to note this?
