### ISSUE TITLE
Feature - improve config UI format

### ISSUE THREAD

**Issue by mcm1957** [foxriver76/ioBroker.notification-manager#8]
Currently the format of the coinfig UI looks like:
![image](https://github.com/foxriver76/ioBroker.notification-manager/assets/28575778/1c05146f-b0fb-4259-9aff-a3756e416292)

I miss the possibility to see whats configured at the first look. One has to open area after area to check which notifications are active and to which adapters they are assigned. So even if one configures the fallback config, it's not visible which notifications have otehr paramaters

Possible solutions I can imagine

- At every area the informatione whether it is active and the up to configured adapters are displayed next to the text or rightbound 
- The configuration is changed to a sort of table mit checkmark active, fixed (!) entry of notification and x columns for adapters
-  a seperated  overview only tab is added which shows the active configuration (including disabled notifications)

Please evaluate

**Comment by foxriver76** [comment]
please check if `1.0.0` shows the information you wanted.
